### PR TITLE
Update branding

### LINKED ISSUE #1629: Update Branding
Update everywhere where it says ProcessMaker 4 to become ProcessMaker Spark.

- [x] Update Composer - Ciev is in the process of updating packagist
- [x] Update NPM - Ciev is in the process of updating npmjs
- [x] Update all references to "vue-form-builder" to spark-screen-builder
- [x] Update package.json
- [x] Update installer
- [x] Console commands
- [x] Homestead.yaml
- [x] Update About page
- [x] Update Page Titles
- [x] CircleCI
- [x] Develop URL https://develop.bpm4.qa.processmaker.net => https://develop.spark.qa.processmaker.net - Dan is working on this now
- [x] spark-connector-send-email https://github.com/ProcessMaker/spark-connector-send-email/pull/14
- [x] spark-sdk-lua, spark-sdk-php, spark-sdk-node
- [x] spark-docker-executor-php, spark-docker-executor-lua, spark-docker-executor-node

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes #1629 

Updates all references of pm4 and bpm to spark

### CODE REVIEW

**Comment by PMQABen** [comment]
Are we going to update `readme.md`?

**Comment by velkymx** [comment]
@milaendo @nolanpro I'm seeing ProcessMaker 4 in the language strings.

**Comment by nolanpro** [comment]
@velkymx those have been updated. We still need a new release of spark-modeler due to https://github.com/ProcessMaker/spark-modeler/pull/313 before this gets merged. Thats why CI is failing

**Comment by PMQABen** [comment]
```
$ grep --exclude-dir=vendor --exclude-dir=storage --exclude-dir=node_modules --exclude-dir=public -R "\bworkflow\b" *
Homestead.yaml:# link a local directory for nayra (workflow engine) development
ProcessMaker/Providers/WorkflowServiceProvider.php:        $this->app->singleton('workflow.manager', function ($app) {
ProcessMaker/Facades/WorkflowManager.php:        return 'workflow.manager';
README.md:ProcessMaker is an open source, workflow management software suite, which includes tools to automate your workflow, design forms, create documents, assign roles and users, create routing rules, and map an individual process quickly and easily. It's relatively lightweight and doesn't require any kind of installation on the client computer. This file describes the requirements and installation steps for the server.
README.md:  * Specify `workflow` as your local database name
after.sh:# Copy over the composer file to our home vagrant user to allow for local package and workflow engine development
bootstrap/autoload.php:    . __DIR__ . '/../workflow/engine/' . PATH_SEPARATOR
config/database.php:    'default' => env('DB_CONNECTION', 'workflow'),
config/database.php:        'workflow' => [
config/database.php:            'database' => env('DB_DATABASE', 'workflow'),
config/database.php:            'username' => env('DB_USERNAME', 'workflow'),
config/queue.php:        'database' => env('DB_CONNECTION', 'workflow'),
config/build.json:                "dest_dir": "workflow/public_html/lib",
config/build.json:                "dest_dir": "workflow/public_html/lib",
config/build.json:                "dir": "workflow/public_html/lib/pmdynaform",
config/build.json:                "dest_dir": "workflow/public_html/lib/pmdynaform/",
config/build.json:                "orig_file": "workflow/engine/templates/cases/pmdynaform.html",
config/build.json:                "dest_dir": "workflow/public_html/lib/pmdynaform/build",
config/build.json:                "dest_dir": "workflow/public_html",
config/build.json:                "dest_dir": "workflow/public_html",
config/build.json:                "dest_dir": "workflow/public_html/lib/",
config/build.json:                "dest_dir": "workflow/public_html/lib/js/",
config/build.json:                "dest_dir": "workflow/public_html/lib/",
config/build.json:                "dest_dir": "workflow/public_html/lib/js",
config/build.json:                    "workflow/public_html/lib/js/wz_jsgraphics.js",
config/build.json:                    "workflow/public_html/lib/js/jquery-1.10.2.min.js",
config/build.json:                    "workflow/public_html/lib/js/underscore-min.js",
config/build.json:                    "workflow/public_html/lib/js/jquery-ui-1.10.3.custom.min.js",
config/build.json:                    "workflow/public_html/lib/js/jquery.layout.min.js",
config/build.json:                    "workflow/public_html/lib/js/modernizr.js",
config/build.json:                    "workflow/public_html/lib/js/restclient.min.js",
config/build.json:                    "workflow/public_html/lib/pmUI/pmui.min.js",
config/build.json:                    "workflow/public_html/lib/mafe/mafe.min.js",
config/build.json:                    "workflow/public_html/lib/mafe/designer.min.js",
config/build.json:                "dest_dir": "workflow/public_html/lib/css",
config/build.json:                    "workflow/public_html/lib/pmUI/pmui.min.css",
config/build.json:                    "workflow/public_html/lib/mafe/mafe.min.css"
config/build.json:                "dest_dir": "workflow/public_html/lib/",
config/build.json:                "dest_dir": "workflow/public_html/lib/",
config/build.json:                "dest_dir": "workflow/public_html/lib/",
config/build.json:                "dest_dir": "workflow/public_html/lib/",
config/build.json:                "dest_dir": "workflow/public_html/lib/",
config/build.json:                "dest_dir": "workflow/public_html/lib/",
resources/lang/en.json:    "Enter the expression that describes the workflow condition": "Enter the expression that describes the workflow condition",
workflow.sql:-- Host: localhost    Database: workflow
```
I know we're supposed to have changed the database name from "workflow" to "spark", so potentially some of these might need to be updated?

**Pull request merged**
