### PR TITLE
Support for spark-package-webentry

### LINKED ISSUE #1742: Web Entry
PRD: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/515014696/Web+Entry+-+Milestone+1

- [x] rename webhooks to web entries
- [x] update WebEntry.vue to include new UI elements and update controller to handle them
- [x] move all these to a package (see the email connector as a guide)
See https://github.com/ProcessMaker/spark-package-webentry/issues

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes #1742 

These are the updates needed in spark to support the https://github.com/ProcessMaker/spark-package-webentry package

Testing instructions are here: https://github.com/ProcessMaker/spark-package-webentry/tree/master/tests/Manual

### CODE REVIEW

**Comment by nolanpro** [comment]
@velkymx [instructions](https://github.com/ProcessMaker/spark-package-webentry/tree/master/tests/Manual) have been updated. The spark-package package is broken and thats why it didn't install correctly. Work around is in instructions. Also updated the web_entry_screen.spark with a stripped down form since may of the elements in the new screen builder are broken (images, tables, record list, etc)

**Comment by PMQABen** [comment]
`The authenticatable type field is required when mode is AUTHENTICATED. The authenticatable id field is required when mode is AUTHENTICATED.`

image
Not seeing anything talking about an "authenticatable id field" in this area. Might need a rewrite.

----
Not sure if related, but the "Sorry, you do not have permission to access this form" error message takes longer than expected to "translate", so for a few seconds or so the user will see

`{{ $t('Sorry, you do not have permission to access this form') }}`

**Comment by nolanpro** [comment]
@PMQABen thats the Web Entry Start Permission, I need to find a way to update the error message

**Comment by PMQABen** [comment]
Yeah, we gotta change around the `The completed url field is required when completed action is URL.` message a little bit too.

Overall though it works as expected.

**Pull request merged**
